name: "Update server"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
 update:
    runs-on: [self-hosted, main]
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Stash current code
      run: git stash
    - name: Get new code
      run: git pull origin main
    - name: Stop ReposHub
      run: pm2 stop reposhub
    - name: Install NPM Packages
      run: npm i
    - name: Start ReposHub
      run: pm2 start reposhub
